### ISSUE TITLE
Custom FirebaseError Handler

### ISSUE THREAD

**Issue by alexsheks** [atomicai/patronusui#18]
Need to add custom ErrorHandler for errors from firebase. Can you do it @myznikovgleb? Basically a component that accepts firebase error response and returns message for user in signin/signup form.

**Comment by myznikovgleb** [comment]
@alexsheks ok, i've assigned it to myself

**Comment by myznikovgleb** [comment]
#### UPD
Need to add custom error messages corresponding to the error responses

- [x]  [auth API errors](https://firebase.google.com/docs/reference/js/auth#autherrorcodes)
- [ ]  [firestore API errors](https://firebase.google.com/docs/reference/js/firestore_#firestoreerrorcode)
- [ ]  [storage API errors](https://firebase.google.com/docs/reference/js/storage.md#storageerrorcode)
