### ISSUE TITLE
Create "highlight" on words

### ISSUE THREAD

**Issue by atomicai** [atomicai/patronusui#7]
Let's add highlighting on the words whenever user tries to search. @myznikovgleb is working on this.

**Comment by myznikovgleb** [comment]
I've assigned the issue to myself
@atomicai Let's discuss details on online meeting or you can put ones at issue description

**Comment by myznikovgleb** [comment]
@alexsheks @atomicai 
The issue seems to be done according to the kanban board
Please, close it in this case
